config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :cameras, only: [:show]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

  namespace :vsaas do
    namespace :api, constraints: { format: :json } do
      post 'login' => 'sessions#create'
      get 'my/cameras' => 'cameras#index'
    end
  end

  root to: 'clients#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  has_secure_password
end

app/models/camera.rb
class Camera < ActiveRecord::Base
  belongs_to :client
  has_and_belongs_to_many :subscribers

  validates :access, inclusion: { in: %w(private public authorized) }
  validates :streamer, presence: true

  def rtsp_url
    @rtsp_url ||= "rtsp://#{streamer}/#{name}?"
  end

  def hls_url
    @hls_url ||= "hls://#{streamer}/#{name}/index-m3u8?"
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  validates :name, presence: true

  has_many :cameras, dependent: :destroy
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  has_and_belongs_to_many :cameras
  has_secure_password

  before_create :create_token

  def update_token
    self.update_attribute :token, generate_token
  end

  private
  def create_token
    self.token ||= generate_token
  end

  def generate_token
    SecureRandom.uuid.tr('-', '')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_admin

  private
  def current_admin
    @current_admin ||= Admin.find_by(id: session[:admin_id]) if session[:admin_id]
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
  before_action :authenticate_admin

  private
  def authenticate_admin
    redirect_to new_session_url unless current_admin
  end
end

app/controllers/cameras_controller.rb
class CamerasController < BaseController
  def show
    @camera = Camera.includes(:subscribers).find(params[:id])
  end
end

app/controllers/clients_controller.rb
class ClientsController < BaseController
  before_action :find_client, only: [:edit, :update, :destroy]
  def index
    @clients = Client.all
  end

  def show
    @client = Client.includes({cameras: :subscribers}).find(params[:id])
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new client_params
    if @client.save
      redirect_to action: :show
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @client.update_attributes client_params
      redirect_to action: :show
    else
      render 'edit'
    end
  end

  def destroy
    @client.destroy
    redirect_to action: :index
  end

  private
  def client_params
    params.require(:client).permit(:name)
  end

  def find_client
    @client = Client.find params[:id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by!(email: params[:email])
    if admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to root_url
    else
      @error = 'Authentication failed'
      render :new
    end
  end

  def destroy
    session[:admin_id] = nil
    redirect_to root_url
  end
end

app/controllers/vsaas/api/base_controller.rb
class Vsaas::Api::BaseController < ::ApplicationController
  before_action :authenticate_subscriber
  skip_before_action :verify_authenticity_token

  private
  def authenticate_subscriber
    render json: { error: 'Unathorized' }, status: 401 unless current_subscriber
  end

  def current_subscriber
    token = request.headers["x-vsaas-session"]
    @current_subscriber ||= Subscriber.find_by(token: token) if token.present?
  end
end

app/controllers/vsaas/api/cameras_controller.rb
class Vsaas::Api::CamerasController < Vsaas::Api::BaseController
  def index
    @cameras = current_subscriber.cameras
  end
end

app/controllers/vsaas/api/sessions_controller.rb
class Vsaas::Api::SessionsController < Vsaas::Api::BaseController
  skip_before_action :authenticate_subscriber, only: :create

  def create
    subscriber = Subscriber.find_by!(email: params[:email])
    if subscriber.authenticate(params[:password])
      subscriber.update_token
      render json: { success: true, session: subscriber.token }
    else
      render json: { success: false }, status: 422
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cameras/show.html.haml
%h1= @camera.name
%small
  belongs to
  = link_to @camera.client.name, @camera.client
%h2 Subscribers
%ul
  - @camera.subscribers.each do |subscriber|
    %li= subscriber.name

app/views/clients/_form.html.haml
= form_for @client do |f|
  = f.text_field :name

  = f.submit

app/views/clients/edit.html.haml
= render 'form'

app/views/clients/index.html.haml
%h1 Clients list
%ul
  - @clients.each do |client|
    %li
      = link_to client.name, client
      = link_to 'x', client, method: :delete, data: { confirm: 'are you sure?' }

= link_to 'add client', new_client_url

app/views/clients/new.html.haml
= render 'form'

app/views/clients/show.html.haml
%h1= @client.name

= link_to 'edit', edit_client_url(@client)
%br
= link_to 'back to index', clients_url

%h2 Cameras
%ul
  - @client.cameras.each do |camera|
    %li= link_to camera.name, camera

%h2 Subscribers
%ul
  - @client.cameras.map(&:subscribers).flatten.uniq.each do |subscriber|
    %li= subscriber.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Erly
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if current_admin
      = link_to 'sign out', sessions_url, method: :delete
    = yield